name: masque
description: An anonymous chat client.
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  intl: ^0.17.0
  login_widget: ^1.0.1
  provider: ^6.0.3
  shared_objects: ^1.0.0+1
  shared_preferences: ^2.0.15
  sp_settings: ^1.0.5
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1
  web_deploy: ^1.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  windows: true
  macos: true
  web: true
  image_path: "assets/icon.png"
