// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnijcLLEpBDhDPzmJVgm6VbSThavUMHS8',
    appId: '1:997175548753:web:f4fa1b619257ec4043d170',
    messagingSenderId: '997175548753',
    projectId: 'masque-ae887',
    authDomain: 'masque-ae887.firebaseapp.com',
    storageBucket: 'masque-ae887.appspot.com',
    measurementId: 'G-B73ZMRL56W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6PXfTph8BiqiYTWtSF-hfbiQCyIiRIY',
    appId: '1:997175548753:android:33acd1ff45a7ca5643d170',
    messagingSenderId: '997175548753',
    projectId: 'masque-ae887',
    storageBucket: 'masque-ae887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwp08skyXXyyL_g4sgk3E-kkZ5GldBb4c',
    appId: '1:997175548753:ios:4fd95563a4f016c743d170',
    messagingSenderId: '997175548753',
    projectId: 'masque-ae887',
    storageBucket: 'masque-ae887.appspot.com',
    iosClientId:
        '997175548753-skdt09jj7s6nq26pu3d9pr0r5fcj51fi.apps.googleusercontent.com',
    iosBundleId: 'com.draco.masque',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwp08skyXXyyL_g4sgk3E-kkZ5GldBb4c',
    appId: '1:997175548753:ios:4fd95563a4f016c743d170',
    messagingSenderId: '997175548753',
    projectId: 'masque-ae887',
    storageBucket: 'masque-ae887.appspot.com',
    iosClientId:
        '997175548753-skdt09jj7s6nq26pu3d9pr0r5fcj51fi.apps.googleusercontent.com',
    iosBundleId: 'com.draco.masque',
  );
}
